name: royale_app
description: A new Flutter application about royale game data.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # Providing a persistent store for simple data. Data is persisted to disk asynchronously.
  # @link: https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.4+3

  # A Flutter plugin to share content from your Flutter app via the platform's share dialog.
  # @link: https://pub.dev/packages/share
  #share: ^0.6.3+1

  # http client from https://github.com/flutterchina/dio.
  dio: ^3.0.4

  # A Flutter plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera.
  # @link: https://pub.dev/packages/image_picker
  #image_picker: ^0.6.1+8

  # Display images from the internet and keep them in the cache directory.
  # @link: https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.0.0-rc.1

  # A collection of loading indicators animated with flutter.
  # @link: https://github.com/jogboms/flutter_spinkit
  #flutter_spinkit: ^4.0.0

  # Android and iOS Toast Library for Flutter.
  # @link: https://github.com/PonnamKarthik/FlutterToast
  fluttertoast: ^3.1.3

  # A mixture between dependency injection (DI) and state management, built with widgets for widgets.
  # @link: https://github.com/rrousselGit/provider
  provider: ^3.1.0+1

  # A flutter plugin for adapting screen and font size.
  # @link: https://github.com/OpenFlutter/flutter_screenutil
  #flutter_screenutil: ^0.6.0

  # Third party platforms provided by http://www.mob.com
  #sharesdk_plugin: ^1.1.6

  # Simple json file-based storage for flutter.(already has contained [path_provider])
  # @link: https://github.com/lesnitsky/flutter_localstorage
  localstorage: ^2.0.0

  # Fluwx makes easier using WeChatSDK on Flutter.
  # @link: https://github.com/OpenFlutter/fluwx
  fluwx: ^1.1.3

  # A permissions plugin for Flutter.
  # @link: https://github.com/Baseflow/flutter-permission-handler
  permission_handler: ^4.0.0
  # Save image or other files to local storage(gallery), based on `image_picker`.
  # @link: https://github.com/hui-z/image_gallery_saver
  image_gallery_saver: ^1.2.2

  # A Flutter staggered grid view which supports multiple columns with rows of varying sizes.
  # @link: https://github.com/letsar/flutter_staggered_grid_view
  flutter_staggered_grid_view: ^0.3.0

  # Swiper for flutter , with multiple layouts, infinite loop.
  # @link: https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6

  # A Flutter plugin for launching a URL in the mobile platform.
  # @link: https://pub.dev/packages/url_launcher
  url_launcher: ^5.2.6

  # This Flutter plugin provides an API for querying information about an application package.
  # @link: https://pub.dev/packages/package_info
  package_info: ^0.4.0+13

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
